import bannerText  from './assets/bannerText.png'
import bannerText1  from './assets/bannerText1.png'
import bannerText2  from './assets/bannerText2.png'
import bannerText3  from './assets/bannerText3.png'
import introduction  from './assets/introduction.png'
import introduction1  from './assets/introduction1.png'
import introduction2  from './assets/introduction2.png'
import introduction3  from './assets/introduction3.png'
import about  from './assets/about.png'
import about1  from './assets/about1.png'
import about2  from './assets/about2.png'
import about3  from './assets/about3.png'
import whitePaper  from './assets/whitePaper.png'
import whitePaper1  from './assets/whitePaper1.png'
import whitePaper2  from './assets/whitePaper2.png'
import whitePaper3  from './assets/whitePaper3.png'
import ecologicalConstruction  from './assets/ecologicalConstruction.png'
import ecologicalConstruction1  from './assets/ecologicalConstruction1.png'
import ecologicalConstruction2  from './assets/ecologicalConstruction2.png'
import ecologicalConstruction3  from './assets/ecologicalConstruction3.png'
import subTitle  from './assets/subTitle.png'
import subTitle1  from './assets/subTitle1.png'
import subTitle2  from './assets/subTitle2.png'
import subTitle3  from './assets/subTitle3.png'
import exchangeTitle  from './assets/exchangeTitle.png'
import exchangeTitle1  from './assets/exchangeTitle1.png'
import exchangeTitle2  from './assets/exchangeTitle2.png'
import exchangeTitle3  from './assets/exchangeTitle3.png'
import square from "./assets/shoppingStructure/square.png";
import square1 from "./assets/shoppingStructure/square1.png";
import square2 from "./assets/shoppingStructure/square2.png";
import jaSquare from "./assets/shoppingStructure/jaSquare.png";
import store from "./assets/shoppingStructure/store.png";
import triangle from "./assets/shoppingStructure/triangle.png";
import leftArc from "./assets/shoppingStructure/leftArc.png";
import rightArc from "./assets/shoppingStructure/rightArc.png";
import buyerDownTriangle from "./assets/shoppingStructure/buyerDownTriangle.png";
import buyerSquare1 from "./assets/shoppingStructure/buyerSquare1.png";
import buyerSquare2 from "./assets/shoppingStructure/buyerSquare2.png";
import buyerSquare3 from "./assets/shoppingStructure/buyerSquare3.png";
import buyerArrow from "./assets/shoppingStructure/buyerArrow.png";
import atmTitle  from './assets/exchangeTitle.png'

import road  from './assets/road.png'
import road1  from './assets/road1.png'
import road2  from './assets/road2.png'
import road3  from './assets/road3.png'
import roadMap  from './assets/roadMap.png'
import roadMap1  from './assets/roadMap1.png'
import roadMap2  from './assets/roadMap2.png'
import roadMap3  from './assets/roadMap3.png'
import conactUs  from './assets/conactUs.png'
import conactUs1  from './assets/conactUs1.png'
import conactUs2  from './assets/conactUs2.png'
import conactUs3  from './assets/conactUs3.png'
const messages = {
    kr: {
      message: {
        menuProjectIntroduction:"프로젝트 안내",
        menuAboutUs:"우리에 관하여",
        menuWhitePaper: '화이트 페이퍼',
        menuEcologicalConstruction:"생태건설",
        menuContactUs:"연락처",
        selectPlaceholder:"언어선택",
        bannerTextImg:bannerText3,
        introductionImg:introduction3,
        introduction1:"Consensus Node는 블록 체인 기술에 기초한 크로스오버 페이징 플랫폼으로서, 스마트 계약과 라이덴 네트워크를 통해 이용자를 위한 크로스오버 이체, 외화 환전, 해외여행, 해외유학, 해외 온라인 쇼핑몰 등등 애플리케이션에서 빠르고 저렴한 간편 지불 서비스를 제공합니다. Consensus Node의 강점은 전통적인 지불 구조의 불필요한 문제를 해결하고 경제 질서를 조정하는 다원소 접속 경로 도구 기반을 갖춘 것입니다.",
        introduction2:"우리는 오프라인 실체 애플리케이션을 기반으로 Consensus Node생태의 빠르고 온전한 발전에 도움을 줄 수 있습니다.",
        aboutImg:about3,
        aboutListTitle1:"우리의 투자 파트너",
        aboutListContent1:"1990년 설립되어 전 세계에 만 개 가까운 편의점을 오픈한 GS Retail그룹 소속 편의점 GS 25.</br> 일본MUFG닛코우증권 산하의 동흥펀드",
        aboutListTitle2:"우리의 기술 지원",
        aboutListContent2:"한국 상장 게임사 NEOWIZ가 Consensus Node 크로스오버 페이징 플랫폼 제작에 참여했으며 또한  장기적인 기술을 지원할 것입니다.",
        aboutListTitle3:"우리의 연구개발 컨설턴트",
        aboutListContent3:"Consensus Node팀은 경희대학교 블록체인 연구개발 실험실과 공동으로 Consensus Node의 블록체인  크로스오버 페이징 플랫폼을 개발했습니다.",
        whitePaperImg:whitePaper3,
        whiteFuntionTitle:"Consensus node 생태 구축의 기초 고리로 제품에는 주로 다음과 같은 4대 기능이 포함되어 있습니다.",
        whiteFuntion1:"크로스오버 페이징, 이체 및 법정화폐 환전을 주요 기능으로 하는 캐시백 기능.",
        whiteFuntion2:"한국과 중국, 일본에서 가장 먼저 크로스 온라인 쇼핑몰에 접속했고 상가에 입주 가능한 플랫폼을 제공하여 이용자가 해외 상품을 편리하게 구입할 수 있도록 해드립니다.",
        whiteFuntion3:"AI 스마트 정보 캡처 기술로 탈중심화 데이터 처리 방식을 실현합니다.",
        whiteFuntion4:"기업 및 개인에 대해 디지털 자산 금융 크레딧 서비스를 제공해 드립니다.",
        ecologicalConstructionImg:ecologicalConstruction3,
        canvasW:"905",
        canvasH:"203",
        storeUrl:store,
        storeUrlX:"3",
        storeUrlY:"45",
        storeUrlW:"101",
        storeUrlH:"101",
        storeText:'상가',
        storeTextX:'50',
        storeTextY:'85',
        storeIdUrl:square,
        storeIdUrlX:'217',
        storeIdUrlY:'6',
        storeIdUrlW:'138',
        storeIdUrlH:'47',
        storeIdText:'신분인증',
        storeIdTextX:'284',
        storeIdTextY:'19',
        leftArcUrl:leftArc,
        leftArcUrlX:"120",
        leftArcUrlY:"26",
        leftArcUrlW:"81",
        leftArcUrlH:"151",
        storeCommodityCertificationUrl:square,
        storeCommodityCertificationUrlX:'217',
        storeCommodityCertificationUrlY:'143',
        storeCommodityCertificationUrlW:'138',
        storeCommodityCertificationUrlH:'47',
        storeCommodityCertificationText:'상품인증',
        storeCommodityCertificationTextX:'284',
        storeCommodityCertificationTextY:'156',
        rightUrl:rightArc,
        rightUrlX:"370",
        rightUrlY:"26",
        rightUrlW:"81",
        rightUrlH:"151",
        storeBondUrl:square1,
        storeBondUrlX:'462',
        storeBondUrlY:'76',
        storeBondUrlW:'229',
        storeBondUrlH:'47',
        storeBondText:'보증금으로 COCO를 저당',
        storeBondTextX:'580',
        storeBondTextY:'90',
        storeTriangleUrl:triangle,
        storeTriangleUrlX:"700",
        storeTriangleUrlY:"90",
        storeTriangleUrlW:"12",
        storeTriangleUrlH:"13",
        storeShoppingMallText:'상가 입주 성공',
        storeShoppingMallTextX:'800',
        storeShoppingMallTextY:'90',
        storeShoppingMallUrl:square2,
        storeShoppingMallUrlX:'728',
        storeShoppingMallUrlY:'76',
        storeShoppingMallUrlW:'148',
        storeShoppingMallUrlH:'47',
        buyerUrl:store,
        buyerUrlX:"27",
        buyerUrlY:"3",
        buyerUrlW:"101",
        buyerUrlH:"101",
        buyerIdUrl:square,
        buyerIdUrlX:"9",
        buyerIdUrlY:"147",
        buyerIdUrlW:"138",
        buyerIdUrlH:"47",
        buyerTriangleUrl:triangle,
        buyerTriangleUrlX:"157",
        buyerTriangleUrlY:"160",
        buyerTriangleUrlW:"16",
        buyerTriangleUrlH:"16",
        buyerText:"소비자",
        buyerTextX:"76",
        buyerTextY:"41",
        buyerDownTriangleUrl:buyerDownTriangle,
        buyerDownTriangleUrlX:"70",
        buyerDownTriangleUrlY:"110",
        buyerDownTriangleUrlW:"16",
        buyerDownTriangleUrlH:"16",
        buyerIdText:"신분인증",
        buyerIdTextX:"70",
        buyerIdTextY:"160",
        buyerShoppingUrl:buyerSquare1,
        buyerShoppingUrlX:"191",
        buyerShoppingUrlY:"149",
        buyerShoppingUrlW:"89",
        buyerShoppingUrlH:"47",
        buyerLeftArcUrl:leftArc,
        buyerLeftArcUrlX:"300",
        buyerLeftArcUrlY:"100",
        buyerLeftArcUrlW:"81",
        buyerLeftArcUrlH:"151",
        buyerShoppingText:"쇼핑",
        buyerShoppingTextX:"230",
        buyerShoppingTextY:"162",
        buyerPayUrl:square,
        buyerPayUrlX:"390",
        buyerPayUrlY:"80",
        buyerPayUrlW:"138",
        buyerPayUrlH:"47",
        buyerPayText:"COCO지불",
        buyerPayTextX:"456",
        buyerPayTextY:"94",
        buyerPayUrl1:square,
        buyerPayUrlX1:"390",
        buyerPayUrlY1:"220",
        buyerPayUrlW1:"138",
        buyerPayUrlH1:"47",
        buyerPayText1:"법정화폐 지불",
        buyerPayText1X:"456",
        buyerPayText1Y:"236",
        buyerRightArcUrl:rightArc,
        buyerRightArcUrlX:"537",
        buyerRightArcUrlY:"100",
        buyerRightArcUrlW:"81",
        buyerRightArcUrlH:"151",
        buyerGoodsReceivedUrl:buyerSquare2,
        buyerGoodsReceivedUrlX:"627",
        buyerGoodsReceivedUrlY:"129",
        buyerGoodsReceivedUrlW:"95",
        buyerGoodsReceivedUrlH:"95",
        buyerGoodsReceivedText:"상품\n수령",
        buyerGoodsReceivedTextX:"674",
        buyerGoodsReceivedTextY:"152",
        buyerTriangleUrl1:triangle,
        buyerTriangleUrlX1:"724",
        buyerTriangleUrlY1:"164",
        buyerTriangleUrlW1:"16",
        buyerTriangleUrlH1:"16",
        buyerDownTriangleUrl1:buyerDownTriangle,
        buyerDownTriangleUrlX1:"666",
        buyerDownTriangleUrlY1:"222",
        buyerDownTriangleUrlW1:"16",
        buyerDownTriangleUrlH1:"16",
        buyerDownTriangleUrl2:buyerDownTriangle,
        buyerDownTriangleUrlX2:"666",
        buyerDownTriangleUrlY2:"264",
        buyerDownTriangleUrlW2:"16",
        buyerDownTriangleUrlH2:"16",
        buyerDownTriangleUrl3:buyerDownTriangle,
        buyerDownTriangleUrlX3:"666",
        buyerDownTriangleUrlY3:"330",
        buyerDownTriangleUrlW3:"16",
        buyerDownTriangleUrlH3:"16",
        buyerDownTriangleUrl4:buyerDownTriangle,
        buyerDownTriangleUrlX4:"666",
        buyerDownTriangleUrlY4:"396",
        buyerDownTriangleUrlW4:"16",
        buyerDownTriangleUrlH4:"16",
        buyerRewardUrl:buyerSquare3,
        buyerRewardUrlX:"380",
        buyerRewardUrlY:"310",
        buyerRewardUrlW:"217",
        buyerRewardUrlH:"123",
        buyerRewardText:"중재에 참여하는 노드\n는  COCO 인센티브를\n받게 됩니다",
        buyerRewardTextX:"470",
        buyerRewardTextY:"340",
        buyerDisputeText:"쟁의",
        buyerDisputeTextX:"670",
        buyerDisputeTextY:"244",
        buyerArbitrationUrl:square,
        buyerArbitrationUrlX:"600",
        buyerArbitrationUrlY:"280",
        buyerArbitrationUrlW:"138",
        buyerArbitrationUrlH:"47",
        buyerArbitrationText:"중재신청",
        buyerArbitrationTextX:"670",
        buyerArbitrationTextY:"294",
        buyerDistributionNodeUrl:square,
        buyerDistributionNodeUrlX:"600",
        buyerDistributionNodeUrlY:"350",
        buyerDistributionNodeUrlW:"138",
        buyerDistributionNodeUrlH:"47",
        buyerDistributionNodeText:"노드 배분",
        buyerDistributionNodeTextX:"670",
        buyerDistributionNodeTextY:"366",
        buyerArbitrationResultUrl:square,
        buyerArbitrationResultUrlX:"600",
        buyerArbitrationResultUrlY:"416",
        buyerArbitrationResultUrlW:"138",
        buyerArbitrationResultUrlH:"47",
        buyerArbitrationResultText:"중재결과",
        buyerArbitrationResultTextX:"670",
        buyerArbitrationResultTextY:"430",
        buyerArrowUrl:buyerArrow,
        buyerArrowUrlX:"750",
        buyerArrowUrlY:"220",
        buyerArrowUrlW:"36",
        buyerArrowUrlH:"220",
        buyerConfirmUrl:buyerSquare2,
        buyerConfirmUrlX:"740",
        buyerConfirmUrlY:"129",
        buyerConfirmUrlW:"95",
        buyerConfirmUrlH:"95",
        buyerConfirmText:"수취\n확인",
        buyerConfirmTextX:"790",
        buyerConfirmTextY:"152",
        buyerTriangleUrl2:triangle,
        buyerTriangleUrlX2:"840",
        buyerTriangleUrlY2:"164",
        buyerTriangleUrlW2:"16",
        buyerTriangleUrlH2:"16",
        buyerFinishUrl:store,
        buyerFinishUrlX:"858",
        buyerFinishUrlY:"129",
        buyerFinishUrlW:"101",
        buyerFinishUrlH:"101",
        buyerFinishText:"거래\n완료",
        buyerFinishTextX:"906",
        buyerFinishTextY:"156",
        subTitleImg:subTitle3,
        exchangeTitleImg:exchangeTitle3,
        atmTitleImg:atmTitle,
        roadImg:road3,
        roadMapImg:roadMap3,
        conactUsImg:conactUs3,
        conactUsTitleHeight:"conactUsTitleHeight3",
        textareaPlaceholder:"필요하시면 언제든지 우리에게 연락 주십시오.",
        button:"제출"
      }
    },
    ja: {
      message: {
        menuProjectIntroduction:"プロジェクトの紹介",
        menuAboutUs:"层私たちについて",
        menuWhitePaper: '白書',
        menuEcologicalConstruction:"エコ建設",
        menuContactUs:"ご連絡ください",
        selectPlaceholder:"言語を選んでください",
        bannerTextImg:bannerText2,
        introductionImg:introduction2,
        introduction1:"Consensus Nodeはブロックチェーン技術に基づく国境を越えた支払いプラットフォームであり、インターネットと雷電ネットワークを介して、ユーザーが海外への振込、為替、海外旅行、海外留学、海外ショッピングなどの応用シーンにおいて、迅速、低コスト、便利な支払いサービスを提供する。Consensus Nodeのメリットは、従来の支払いシーン構造の冗長性問題を解決し、経済的秩序や多要素結合パスを調整するツールベースを備えていることである。",
        introduction2:"我々はオフラインエンティの応用シーンをベースにしており、Consensus Node生態が速く、着実に発展するのを助けることができる．",
        aboutImg:about2,
        aboutListTitle1:"私たちの投資パートナーについて",
        aboutListContent1:"1990年に設立された、世界に1万軒近くのコンビニを開設した韓国GSRetailグループ傘下コンビニGS 25。</br>日本MUFG日・証券傘下東興基金会。",
        aboutListTitle2:"私たちの技術サポート",
        aboutListContent2:"韓国上場ゲーム会社NEOWIZは、Consensus Node国境を越えた支払いプラットフォームの作成に参加し、長期的な技術サポートを提供してくれる。",
        aboutListTitle3:"私たちの研究開発コンサルタント",
        aboutListContent3:"Consensus Nodeチームと韓国慶熙大学（Kyung Hee ∪niversity）ブロックチェーンの研究開発実験は共同でConsensus Nodeブロックチェーンが国境を越えた支払いプラットフォームを開発した。",
        whitePaperImg:whitePaper2,
        whiteFuntionTitle:"Consensus nodeの生態構築の基本的な一環であり、製品は主に四つの機能を含んでいる。",
        whiteFuntion1:"国境を越えた支払い、振込、法通貨の振り替えを主な機能とする財布機能です。",
        whiteFuntion2:"中国、日本、韓国が率先して接続したオンライン国境を越えたショッピング、企業に入駐できるプラットフォームを提供して、ユーザーが海外の商品を購入するのに便利です。",
        whiteFuntion3:"ＡＩスマート情報取り込み技術は、センターへのデータ処理方式を実現する．",
        whiteFuntion4:"企業及び個人に対してデジタル資産金融信用サービスを提供する。",
        ecologicalConstructionImg:ecologicalConstruction2,
        canvasW:"940",
        canvasH:"203",
        storeUrl:store,
        storeUrlX:"3",
        storeUrlY:"45",
        storeUrlW:"101",
        storeUrlH:"101",
        storeText:'商家',
        storeTextX:'50',
        storeTextY:'85',
        storeIdUrl:square,
        storeIdUrlX:'217',
        storeIdUrlY:'6',
        storeIdUrlW:'138',
        storeIdUrlH:'47',
        storeIdText:'身分認証',
        storeIdTextX:'284',
        storeIdTextY:'19',
        leftArcUrl:leftArc,
        leftArcUrlX:"120",
        leftArcUrlY:"26",
        leftArcUrlW:"81",
        leftArcUrlH:"151",
        storeCommodityCertificationUrl:square,
        storeCommodityCertificationUrlX:'217',
        storeCommodityCertificationUrlY:'143',
        storeCommodityCertificationUrlW:'138',
        storeCommodityCertificationUrlH:'47',
        storeCommodityCertificationText:'商品認証',
        storeCommodityCertificationTextX:'284',
        storeCommodityCertificationTextY:'156',
        rightUrl:rightArc,
        rightUrlX:"370",
        rightUrlY:"26",
        rightUrlW:"81",
        rightUrlH:"151",
        storeBondUrl:square1,
        storeBondUrlX:'462',
        storeBondUrlY:'76',
        storeBondUrlW:'229',
        storeBondUrlH:'47',
        storeBondText:'COCOを保証金として',
        storeBondTextX:'580',
        storeBondTextY:'90',
        storeTriangleUrl:triangle,
        storeTriangleUrlX:"700",
        storeTriangleUrlY:"90",
        storeTriangleUrlW:"12",
        storeTriangleUrlH:"13",
        storeShoppingMallText:'ショッピングへの\n入居に成功する',
        storeShoppingMallTextX:'800',
        storeShoppingMallTextY:'76',
        storeShoppingMallUrl:square2,
        storeShoppingMallUrlX:'710',
        storeShoppingMallUrlY:'56',
        storeShoppingMallUrlW:'180',
        storeShoppingMallUrlH:'91',
        buyerUrl:store,
        buyerUrlX:"27",
        buyerUrlY:"3",
        buyerUrlW:"101",
        buyerUrlH:"101",
        buyerIdUrl:square,
        buyerIdUrlX:"9",
        buyerIdUrlY:"147",
        buyerIdUrlW:"138",
        buyerIdUrlH:"47",
        buyerTriangleUrl:triangle,
        buyerTriangleUrlX:"157",
        buyerTriangleUrlY:"160",
        buyerTriangleUrlW:"16",
        buyerTriangleUrlH:"16",
        buyerText:"消費者",
        buyerTextX:"76",
        buyerTextY:"41",
        buyerDownTriangleUrl:buyerDownTriangle,
        buyerDownTriangleUrlX:"70",
        buyerDownTriangleUrlY:"110",
        buyerDownTriangleUrlW:"16",
        buyerDownTriangleUrlH:"16",
        buyerIdText:"ID認証",
        buyerIdTextX:"70",
        buyerIdTextY:"160",
        buyerShoppingUrl:buyerSquare1,
        buyerShoppingUrlX:"181",
        buyerShoppingUrlY:"149",
        buyerShoppingUrlW:"128",
        buyerShoppingUrlH:"47",
        buyerLeftArcUrl:leftArc,
        buyerLeftArcUrlX:"310",
        buyerLeftArcUrlY:"100",
        buyerLeftArcUrlW:"81",
        buyerLeftArcUrlH:"151",
        buyerShoppingText:"ショッピング",
        buyerShoppingTextX:"246",
        buyerShoppingTextY:"162",
        buyerPayUrl:square,
        buyerPayUrlX:"390",
        buyerPayUrlY:"80",
        buyerPayUrlW:"138",
        buyerPayUrlH:"47",
        buyerPayText:"COCO支払い",
        buyerPayTextX:"456",
        buyerPayTextY:"94",
        buyerPayUrl1:square,
        buyerPayUrlX1:"390",
        buyerPayUrlY1:"220",
        buyerPayUrlW1:"138",
        buyerPayUrlH1:"47",
        buyerPayText1:"支払い通貨",
        buyerPayText1X:"456",
        buyerPayText1Y:"236",
        buyerRightArcUrl:rightArc,
        buyerRightArcUrlX:"537",
        buyerRightArcUrlY:"100",
        buyerRightArcUrlW:"81",
        buyerRightArcUrlH:"151",
        buyerGoodsReceivedUrl:buyerSquare2,
        buyerGoodsReceivedUrlX:"627",
        buyerGoodsReceivedUrlY:"129",
        buyerGoodsReceivedUrlW:"95",
        buyerGoodsReceivedUrlH:"95",
        buyerGoodsReceivedText:"商品\nの受領",
        buyerGoodsReceivedTextX:"674",
        buyerGoodsReceivedTextY:"152",
        buyerTriangleUrl1:triangle,
        buyerTriangleUrlX1:"724",
        buyerTriangleUrlY1:"164",
        buyerTriangleUrlW1:"16",
        buyerTriangleUrlH1:"16",
        buyerDownTriangleUrl1:buyerDownTriangle,
        buyerDownTriangleUrlX1:"666",
        buyerDownTriangleUrlY1:"222",
        buyerDownTriangleUrlW1:"16",
        buyerDownTriangleUrlH1:"16",
        buyerDownTriangleUrl2:buyerDownTriangle,
        buyerDownTriangleUrlX2:"666",
        buyerDownTriangleUrlY2:"264",
        buyerDownTriangleUrlW2:"16",
        buyerDownTriangleUrlH2:"16",
        buyerDownTriangleUrl3:buyerDownTriangle,
        buyerDownTriangleUrlX3:"666",
        buyerDownTriangleUrlY3:"330",
        buyerDownTriangleUrlW3:"16",
        buyerDownTriangleUrlH3:"16",
        buyerDownTriangleUrl4:buyerDownTriangle,
        buyerDownTriangleUrlX4:"666",
        buyerDownTriangleUrlY4:"396",
        buyerDownTriangleUrlW4:"16",
        buyerDownTriangleUrlH4:"16",
        buyerRewardUrl:buyerSquare3,
        buyerRewardUrlX:"360",
        buyerRewardUrlY:"300",
        buyerRewardUrlW:"233",
        buyerRewardUrlH:"123",
        buyerRewardText:"アービトレーションに\n参加したノードは\nCOCOの奨励を受ける",
        buyerRewardTextX:"460",
        buyerRewardTextY:"320",
        buyerDisputeText:"紛争が出る",
        buyerDisputeTextX:"670",
        buyerDisputeTextY:"244",
        buyerArbitrationUrl:square,
        buyerArbitrationUrlX:"600",
        buyerArbitrationUrlY:"280",
        buyerArbitrationUrlW:"138",
        buyerArbitrationUrlH:"47",
        buyerArbitrationText:"仲裁の提出",
        buyerArbitrationTextX:"670",
        buyerArbitrationTextY:"294",
        buyerDistributionNodeUrl:square,
        buyerDistributionNodeUrlX:"600",
        buyerDistributionNodeUrlY:"350",
        buyerDistributionNodeUrlW:"138",
        buyerDistributionNodeUrlH:"47",
        buyerDistributionNodeText:"割当ノード",
        buyerDistributionNodeTextX:"670",
        buyerDistributionNodeTextY:"366",
        buyerArbitrationResultUrl:square,
        buyerArbitrationResultUrlX:"600",
        buyerArbitrationResultUrlY:"416",
        buyerArbitrationResultUrlW:"138",
        buyerArbitrationResultUrlH:"47",
        buyerArbitrationResultText:"仲裁結果",
        buyerArbitrationResultTextX:"670",
        buyerArbitrationResultTextY:"430",
        buyerArrowUrl:buyerArrow,
        buyerArrowUrlX:"750",
        buyerArrowUrlY:"220",
        buyerArrowUrlW:"36",
        buyerArrowUrlH:"220",
        buyerConfirmUrl:buyerSquare2,
        buyerConfirmUrlX:"740",
        buyerConfirmUrlY:"129",
        buyerConfirmUrlW:"95",
        buyerConfirmUrlH:"95",
        buyerConfirmText:"荷受\n確認",
        buyerConfirmTextX:"786",
        buyerConfirmTextY:"152",
        buyerTriangleUrl2:triangle,
        buyerTriangleUrlX2:"840",
        buyerTriangleUrlY2:"164",
        buyerTriangleUrlW2:"16",
        buyerTriangleUrlH2:"16",
        buyerFinishUrl:store,
        buyerFinishUrlX:"858",
        buyerFinishUrlY:"129",
        buyerFinishUrlW:"101",
        buyerFinishUrlH:"101",
        buyerFinishText:"取引\n完了",
        buyerFinishTextX:"910",
        buyerFinishTextY:"156",
        subTitleImg:subTitle2,
        exchangeTitleImg:exchangeTitle2,
        atmTitleImg:atmTitle,
        roadImg:road2,
        roadMapImg:roadMap2,
        conactUsImg:conactUs2,
        conactUsTitleHeight:"conactUsTitleHeight2",
        textareaPlaceholder:"ご要望がありましたら、ご連絡ください",
        button:"提出"
      }
    },
    en: {
      message: {
        menuProjectIntroduction:"Project Introduction",
        menuAboutUs:"About Us",
        menuWhitePaper: 'White Paper',
        menuEcologicalConstruction:"Ecological Construction",
        menuContactUs:"Contact Us",
        selectPlaceholder:"Select Language",
        bannerTextImg:bannerText1,
        introductionImg:introduction1,
        introduction1:"Consensus Node is a cross-border payment platform based on blockchain technology, which aims to provide fast, low-cost, and convenient payment services for users in the application scenarios of international transfer, exchange, outbound travel, study abroad, and cross-border e-commerce, etc. through smart contracts and Raiden Network. It solves the problem of structural redundancy of traditional payment scenarios, and has the basis of adjusting economic order and multi-element coupling path tools.",
        introduction2:"We have a variety of offline entity application scenarios to help the Consensus Node ecosystem develop quickly and strongly.",
        aboutListTitle1:"OUR INVESTMENT PARTNERS",
        aboutListContent1:"The convenience store GS 25 under South Korea GS Retail Group was established in 1990, opening nearly 10,000 convenience stores around the world.</br>Japan Dongxing Foundation of the Mitsubishi UFJ Securities.",
        aboutImg:about1,
        aboutListTitle2:"TECHNICAL SUPPORT",
        aboutListContent2:"NEOWIZ, a Korean listed game company, is involved in the development of the Consensus Node cross-border payment platform and provides us with long-term technical support.",
        aboutListTitle3:"RESEARCH AND DEVELOPMENT CONSULTANT",
        aboutListContent3:"The Consensus Node team joins hand with Kyung Hee University's blockchain R&D laboratory to develop the Consensus Node blockchain cross-border payment platform.",
        whitePaperImg:whitePaper1,
        whiteFuntionTitle:"The basic link of the ecological construction of the Consensus node. The product mainly includes four major functions:",
        whiteFuntion1:"An electronic wallet with cross-border payments, transfers, and currency exchange as its primary function.",
        whiteFuntion2:"An online cross-border mall that is first accessed by China, Japan and South Korea , providing a platform for merchants to join in, so that users can purchase overseas products.",
        whiteFuntion3:"AI intelligent information acquisition technology to achieve decentralized data processing.",
        whiteFuntion4:"Provide digital asset financial credit services for businesses and individuals.",
        ecologicalConstructionImg:ecologicalConstruction1,
        canvasW:"968",
        canvasH:"215",
        storeUrl:square1,
        storeUrlX:"9",
        storeUrlY:"70",
        storeUrlW:"156",
        storeUrlH:"66",
        storeText:'Merchant',
        storeTextX:'86',
        storeTextY:'92',
        storeIdUrl:square,
        storeIdUrlX:'250',
        storeIdUrlY:'10',
        storeIdUrlW:'138',
        storeIdUrlH:'47',
        storeIdText:'Identity',
        storeIdTextX:'322',
        storeIdTextY:'24',
        leftArcUrl:leftArc,
        leftArcUrlX:"166",
        leftArcUrlY:"26",
        leftArcUrlW:"81",
        leftArcUrlH:"151",
        storeCommodityCertificationUrl:jaSquare,
        storeCommodityCertificationUrlX:'250',
        storeCommodityCertificationUrlY:'124',
        storeCommodityCertificationUrlW:'138',
        storeCommodityCertificationUrlH:'79',
        storeCommodityCertificationText:'Commodity\nCertification',
        storeCommodityCertificationTextX:'316',
        storeCommodityCertificationTextY:'136',
        rightUrl:rightArc,
        rightUrlX:"390",
        rightUrlY:"26",
        rightUrlW:"81",
        rightUrlH:"151",
        storeBondText:'Mortgage COCO\nas Margin',
        storeBondTextX:'566',
        storeBondTextY:'76',
        storeBondUrl:jaSquare,
        storeBondUrlX:'468',
        storeBondUrlY:'56',
        storeBondUrlW:'201',
        storeBondUrlH:'89',
        storeTriangleUrl:triangle,
        storeTriangleUrlX:"670",
        storeTriangleUrlY:"90",
        storeTriangleUrlW:"12",
        storeTriangleUrlH:"13",
        storeShoppingMallText:'Allowed to open\na store in the mall',
        storeShoppingMallTextX:'778',
        storeShoppingMallTextY:'76',
        storeShoppingMallUrl:jaSquare,
        storeShoppingMallUrlX:'688',
        storeShoppingMallUrlY:'56',
        storeShoppingMallUrlW:'180',
        storeShoppingMallUrlH:'89',
        buyerUrl:square1,
        buyerUrlX:"9",
        buyerUrlY:"6",
        buyerUrlW:"138",
        buyerUrlH:"47",
        buyerIdUrl:jaSquare,
        buyerIdUrlX:"9",
        buyerIdUrlY:"100",
        buyerIdUrlW:"138",
        buyerIdUrlH:"70",
        buyerText:"Consumer",
        buyerTextX:"74",
        buyerTextY:"20",
        buyerIdText:"Identity\nAuthentication",
        buyerIdTextX:"76",
        buyerIdTextY:"110",
        buyerTriangleUrl:triangle,
        buyerTriangleUrlX:"157",
        buyerTriangleUrlY:"126",
        buyerTriangleUrlW:"16",
        buyerTriangleUrlH:"16",
        buyerDownTriangleUrl:buyerDownTriangle,
        buyerDownTriangleUrlX:"70",
        buyerDownTriangleUrlY:"72",
        buyerDownTriangleUrlW:"16",
        buyerDownTriangleUrlH:"16",
        buyerShoppingUrl:buyerSquare1,
        buyerShoppingUrlX:"180",
        buyerShoppingUrlY:"116",
        buyerShoppingUrlW:"98",
        buyerShoppingUrlH:"47",
        buyerLeftArcUrl:leftArc,
        buyerLeftArcUrlX:"280",
        buyerLeftArcUrlY:"60",
        buyerLeftArcUrlW:"81",
        buyerLeftArcUrlH:"151",
        buyerShoppingText:"Shopping",
        buyerShoppingTextX:"228",
        buyerShoppingTextY:"128",
        buyerPayUrl:square,
        buyerPayUrlX:"360",
        buyerPayUrlY:"44",
        buyerPayUrlW:"138",
        buyerPayUrlH:"47",
        buyerPayText:"Pay COCO",
        buyerPayTextX:"430",
        buyerPayTextY:"56",
        buyerPayUrl1:jaSquare,
        buyerPayUrlX1:"362",
        buyerPayUrlY1:"180",
        buyerPayUrlW1:"128",
        buyerPayUrlH1:"64",
        buyerPayText1:"Payment of\nlegal currency",
        buyerPayText1X:"426",
        buyerPayText1Y:"186",
        buyerRightArcUrl:rightArc,
        buyerRightArcUrlX:"496",
        buyerRightArcUrlY:"60",
        buyerRightArcUrlW:"81",
        buyerRightArcUrlH:"151",
        buyerGoodsReceivedUrl:buyerSquare2,
        buyerGoodsReceivedUrlX:"590",
        buyerGoodsReceivedUrlY:"89",
        buyerGoodsReceivedUrlW:"95",
        buyerGoodsReceivedUrlH:"95",
        buyerGoodsReceivedText:"Receipt\nof goods",
        buyerGoodsReceivedTextX:"636",
        buyerGoodsReceivedTextY:"110",
        buyerTriangleUrl1:triangle,
        buyerTriangleUrlX1:"690",
        buyerTriangleUrlY1:"130",
        buyerTriangleUrlW1:"16",
        buyerTriangleUrlH1:"16",
        buyerDownTriangleUrl1:buyerDownTriangle,
        buyerDownTriangleUrlX1:"626",
        buyerDownTriangleUrlY1:"180",
        buyerDownTriangleUrlW1:"16",
        buyerDownTriangleUrlH1:"16",
        buyerDownTriangleUrl2:buyerDownTriangle,
        buyerDownTriangleUrlX2:"626",
        buyerDownTriangleUrlY2:"240",
        buyerDownTriangleUrlW2:"16",
        buyerDownTriangleUrlH2:"16",
        buyerDownTriangleUrl3:buyerDownTriangle,
        buyerDownTriangleUrlX3:"626",
        buyerDownTriangleUrlY3:"326",
        buyerDownTriangleUrlW3:"16",
        buyerDownTriangleUrlH3:"16",
        buyerDownTriangleUrl4:buyerDownTriangle,
        buyerDownTriangleUrlX4:"626",
        buyerDownTriangleUrlY4:"410",
        buyerDownTriangleUrlW4:"16",
        buyerDownTriangleUrlH4:"16",
        buyerDisputeText:"Controversy",
        buyerDisputeTextX:"626",
        buyerDisputeTextY:"240",
        buyerArbitrationUrl:square,
        buyerArbitrationUrlX:"560",
        buyerArbitrationUrlY:"266",
        buyerArbitrationUrlW:"156",
        buyerArbitrationUrlH:"47",
        buyerArbitrationText:"Controversy",
        buyerArbitrationTextX:"644",
        buyerArbitrationTextY:"280",
        buyerRewardUrl:buyerSquare3,
        buyerRewardUrlX:"326",
        buyerRewardUrlY:"310",
        buyerRewardUrlW:"237",
        buyerRewardUrlH:"123",
        buyerRewardText:"The node participating \n in the arbitration shall \n receive COCO as a \n reward.",
        buyerRewardTextX:"430",
        buyerRewardTextY:"324",
        buyerDisputeText:"Controversy",
        buyerDisputeTextX:"630",
        buyerDisputeTextY:"210",
        buyerDistributionNodeUrl:jaSquare,
        buyerDistributionNodeUrlX:"560",
        buyerDistributionNodeUrlY:"346",
        buyerDistributionNodeUrlW:"156",
        buyerDistributionNodeUrlH:"70",
        buyerDistributionNodeText:"Distributing\nthe node",
        buyerDistributionNodeTextX:"636",
        buyerDistributionNodeTextY:"356",
        buyerArbitrationResultUrl:square,
        buyerArbitrationResultUrlX:"560",
        buyerArbitrationResultUrlY:"430",
        buyerArbitrationResultUrlW:"158",
        buyerArbitrationResultUrlH:"47",
        buyerArbitrationResultText:"Arbitration results",
        buyerArbitrationResultTextX:"640",
        buyerArbitrationResultTextY:"442",
        buyerArrowUrl:buyerArrow,
        buyerArrowUrlX:"720",
        buyerArrowUrlY:"180",
        buyerArrowUrlW:"60",
        buyerArrowUrlH:"280",
        buyerConfirmUrl:buyerSquare2,
        buyerConfirmUrlX:"710",
        buyerConfirmUrlY:"89",
        buyerConfirmUrlW:"120",
        buyerConfirmUrlH:"95",
        buyerConfirmText:"Confirmation\nof recei",
        buyerConfirmTextX:"770",
        buyerConfirmTextY:"116",
        buyerTriangleUrl2:triangle,
        buyerTriangleUrlX2:"840",
        buyerTriangleUrlY2:"130",
        buyerTriangleUrlW2:"16",
        buyerTriangleUrlH2:"16",
        buyerFinishUrl:buyerSquare2,
        buyerFinishUrlX:"858",
        buyerFinishUrlY:"89",
        buyerFinishUrlW:"130",
        buyerFinishUrlH:"101",
        buyerFinishText:"Completion \nof transactions",
        buyerFinishTextX:"922",
        buyerFinishTextY:"114",
        subTitleImg:subTitle1,
        exchangeTitleImg:exchangeTitle1,
        atmTitleImg:atmTitle,
        roadImg:road1,
        roadMapImg:roadMap1,
        conactUsImg:conactUs1,
        conactUsTitleHeight:"conactUsTitleHeight1",
        textareaPlaceholder:"If you have any further questions, please feel free to contact us.",
        button:"Submit"
      }
    },
    cn: {
      message: {
        menuProjectIntroduction:"项目介绍",
        menuAboutUs:"关于我们",
        menuWhitePaper: '白皮书',
        menuEcologicalConstruction:"生态建设",
        menuContactUs:"联系我们",
        selectPlaceholder:"选择语言",
        bannerTextImg: bannerText,
        introductionImg:introduction,
        introduction1:"Consensus Node是一个基于区块链技术的跨境支付平台，通过智能合约和雷电网络，为用户在跨国转账、换汇、出境旅游、出国留学、与海外线上商城购物等应用场景中，提供快速、低成本、便捷的支付服务。",
        introduction2:"我们拥有线下实体应用场景作为的基础，可以帮助Consensus Node生态快速，稳健的发展。",
        aboutImg:about,
        aboutListTitle1:"我们的投资伙伴",
        aboutListContent1:"成立于1990年，在全球开设近万家便利店的，韩国 GS Retail集团旗下便利店品GS 25。</br>日本MUFG日與证券旗下东兴基金会。",
        aboutListTitle2:"我们的技术支持",
        aboutListContent2:"我们的技术由韩国上市游戏公司NEOWIZ提供，研发并制作Consensus Node跨境支付平台，并将为我们提供长期技术支持。",
        aboutListTitle3:"我们的研发顾问",
        aboutListContent3:"Consensus Node团队联合韩国庆熙大学（Kyung Hee ∪niversity）区块链研发实验共同研发了Consensus Node区块链跨境支付平台。",
        whitePaperImg:whitePaper,
        whiteFuntionTitle:"Consensus node 生态构建的基础环节， 产品主要包含四大功能：",
        whiteFuntion1:"以跨境支付、转账和法币换汇作为主要功能的钱包功能。",
        whiteFuntion2:"由中国、日本和韩国率先接入的线上跨境商城,为商家提供可入驻的平台,方便用户购买海外的商品。",
        whiteFuntion3:"AI智能信息抓取技术,实现去中心的数据处理方式。",
        whiteFuntion4:"对企业及个人提供数字资产金融信贷服务。",
        ecologicalConstructionImg:ecologicalConstruction,
        canvasW:"905",
        canvasH:"203",
        storeUrl:store,
        storeUrlX:"3",
        storeUrlY:"45",
        storeUrlW:"101",
        storeUrlH:"101",
        storeText:'商家',
        storeTextX:'50',
        storeTextY:'85',
        storeIdUrl:square,
        storeIdUrlX:'217',
        storeIdUrlY:'6',
        storeIdUrlW:'138',
        storeIdUrlH:'47',
        storeIdText:'身份认证',
        storeIdTextX:'284',
        storeIdTextY:'19',
        leftArcUrl:leftArc,
        leftArcUrlX:"120",
        leftArcUrlY:"26",
        leftArcUrlW:"81",
        leftArcUrlH:"151",
        storeCommodityCertificationUrl:square,
        storeCommodityCertificationUrlX:'217',
        storeCommodityCertificationUrlY:'143',
        storeCommodityCertificationUrlW:'138',
        storeCommodityCertificationUrlH:'47',
        storeCommodityCertificationText:'商品认证',
        storeCommodityCertificationTextX:'284',
        storeCommodityCertificationTextY:'156',
        rightUrl:rightArc,
        rightUrlX:"370",
        rightUrlY:"26",
        rightUrlW:"81",
        rightUrlH:"151",
        storeBondUrl:square1,
        storeBondUrlX:'462',
        storeBondUrlY:'76',
        storeBondUrlW:'229',
        storeBondUrlH:'47',
        storeBondText:'抵押COCO作为保证金',
        storeBondTextX:'580',
        storeBondTextY:'90',
        storeTriangleUrl:triangle,
        storeTriangleUrlX:"700",
        storeTriangleUrlY:"90",
        storeTriangleUrlW:"12",
        storeTriangleUrlH:"13",
        storeShoppingMallText:'成功入住商城',
        storeShoppingMallTextX:'800',
        storeShoppingMallTextY:'90',
        storeShoppingMallUrl:square2,
        storeShoppingMallUrlX:'728',
        storeShoppingMallUrlY:'76',
        storeShoppingMallUrlW:'148',
        storeShoppingMallUrlH:'47',
        buyerUrl:store,
        buyerUrlX:"27",
        buyerUrlY:"3",
        buyerUrlW:"101",
        buyerUrlH:"101",
        buyerIdUrl:square,
        buyerIdUrlX:"9",
        buyerIdUrlY:"147",
        buyerIdUrlW:"138",
        buyerIdUrlH:"47",
        buyerTriangleUrl:triangle,
        buyerTriangleUrlX:"157",
        buyerTriangleUrlY:"160",
        buyerTriangleUrlW:"16",
        buyerTriangleUrlH:"16",
        buyerText:"消费者",
        buyerTextX:"76",
        buyerTextY:"41",
        buyerDownTriangleUrl:buyerDownTriangle,
        buyerDownTriangleUrlX:"70",
        buyerDownTriangleUrlY:"110",
        buyerDownTriangleUrlW:"16",
        buyerDownTriangleUrlH:"16",
        buyerIdText:"身份认证",
        buyerIdTextX:"70",
        buyerIdTextY:"160",
        buyerShoppingUrl:buyerSquare1,
        buyerShoppingUrlX:"191",
        buyerShoppingUrlY:"149",
        buyerShoppingUrlW:"89",
        buyerShoppingUrlH:"47",
        buyerLeftArcUrl:leftArc,
        buyerLeftArcUrlX:"300",
        buyerLeftArcUrlY:"100",
        buyerLeftArcUrlW:"81",
        buyerLeftArcUrlH:"151",
        buyerShoppingText:"购物",
        buyerShoppingTextX:"230",
        buyerShoppingTextY:"162",
        buyerPayUrl:square,
        buyerPayUrlX:"390",
        buyerPayUrlY:"80",
        buyerPayUrlW:"138",
        buyerPayUrlH:"47",
        buyerPayText:"支付COCO",
        buyerPayTextX:"456",
        buyerPayTextY:"94",
        buyerPayUrl1:square,
        buyerPayUrlX1:"390",
        buyerPayUrlY1:"220",
        buyerPayUrlW1:"138",
        buyerPayUrlH1:"47",
        buyerPayText1:"支付法币",
        buyerPayText1X:"456",
        buyerPayText1Y:"236",
        buyerRightArcUrl:rightArc,
        buyerRightArcUrlX:"537",
        buyerRightArcUrlY:"100",
        buyerRightArcUrlW:"81",
        buyerRightArcUrlH:"151",
        buyerGoodsReceivedUrl:buyerSquare2,
        buyerGoodsReceivedUrlX:"627",
        buyerGoodsReceivedUrlY:"129",
        buyerGoodsReceivedUrlW:"95",
        buyerGoodsReceivedUrlH:"95",
        buyerGoodsReceivedText:"收到\n商品",
        buyerGoodsReceivedTextX:"674",
        buyerGoodsReceivedTextY:"152",
        buyerTriangleUrl1:triangle,
        buyerTriangleUrlX1:"724",
        buyerTriangleUrlY1:"164",
        buyerTriangleUrlW1:"16",
        buyerTriangleUrlH1:"16",
        buyerDownTriangleUrl1:buyerDownTriangle,
        buyerDownTriangleUrlX1:"666",
        buyerDownTriangleUrlY1:"222",
        buyerDownTriangleUrlW1:"16",
        buyerDownTriangleUrlH1:"16",
        buyerDownTriangleUrl2:buyerDownTriangle,
        buyerDownTriangleUrlX2:"666",
        buyerDownTriangleUrlY2:"264",
        buyerDownTriangleUrlW2:"16",
        buyerDownTriangleUrlH2:"16",
        buyerDownTriangleUrl3:buyerDownTriangle,
        buyerDownTriangleUrlX3:"666",
        buyerDownTriangleUrlY3:"330",
        buyerDownTriangleUrlW3:"16",
        buyerDownTriangleUrlH3:"16",
        buyerDownTriangleUrl4:buyerDownTriangle,
        buyerDownTriangleUrlX4:"666",
        buyerDownTriangleUrlY4:"396",
        buyerDownTriangleUrlW4:"16",
        buyerDownTriangleUrlH4:"16",
        buyerRewardUrl:buyerSquare3,
        buyerRewardUrlX:"418",
        buyerRewardUrlY:"300",
        buyerRewardUrlW:"163",
        buyerRewardUrlH:"123",
        buyerRewardText:"参与仲裁的\n节点会获得\nCOCO奖励",
        buyerRewardTextX:"480",
        buyerRewardTextY:"320",
        buyerDisputeText:"出现争议",
        buyerDisputeTextX:"670",
        buyerDisputeTextY:"244",
        buyerArbitrationUrl:square,
        buyerArbitrationUrlX:"600",
        buyerArbitrationUrlY:"280",
        buyerArbitrationUrlW:"138",
        buyerArbitrationUrlH:"47",
        buyerArbitrationText:"提出仲裁",
        buyerArbitrationTextX:"670",
        buyerArbitrationTextY:"294",
        buyerDistributionNodeUrl:square,
        buyerDistributionNodeUrlX:"600",
        buyerDistributionNodeUrlY:"350",
        buyerDistributionNodeUrlW:"138",
        buyerDistributionNodeUrlH:"47",
        buyerDistributionNodeText:"分配节点",
        buyerDistributionNodeTextX:"670",
        buyerDistributionNodeTextY:"366",
        buyerArbitrationResultUrl:square,
        buyerArbitrationResultUrlX:"600",
        buyerArbitrationResultUrlY:"416",
        buyerArbitrationResultUrlW:"138",
        buyerArbitrationResultUrlH:"47",
        buyerArbitrationResultText:"仲裁结果",
        buyerArbitrationResultTextX:"670",
        buyerArbitrationResultTextY:"430",
        buyerArrowUrl:buyerArrow,
        buyerArrowUrlX:"750",
        buyerArrowUrlY:"220",
        buyerArrowUrlW:"36",
        buyerArrowUrlH:"220",
        buyerConfirmUrl:buyerSquare2,
        buyerConfirmUrlX:"740",
        buyerConfirmUrlY:"129",
        buyerConfirmUrlW:"95",
        buyerConfirmUrlH:"95",
        buyerConfirmText:"确认\n收货",
        buyerConfirmTextX:"790",
        buyerConfirmTextY:"152",
        buyerTriangleUrl2:triangle,
        buyerTriangleUrlX2:"840",
        buyerTriangleUrlY2:"164",
        buyerTriangleUrlW2:"16",
        buyerTriangleUrlH2:"16",
        buyerFinishUrl:buyerSquare2,
        buyerFinishUrlX:"858",
        buyerFinishUrlY:"129",
        buyerFinishUrlW:"130",
        buyerFinishUrlH:"101",
        buyerFinishText:"完成\n交易",
        buyerFinishTextX:"920",
        buyerFinishTextY:"152",
        subTitleImg:subTitle,
        exchangeTitleImg:exchangeTitle,
        atmTitleImg:atmTitle,
        roadImg:road,
        roadMapImg:roadMap,
        conactUsImg:conactUs,
        conactUsTitleHeight:"conactUsTitleHeight",
        textareaPlaceholder:"如果您有什么需要，请联络我们…",
        button:"提交"
      }
    }
  }
  export  default messages;